//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namal_WpfApplication.N_SServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment_tbl", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Payment_tbl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Payment_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Payment_Invoice_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Payment_Report Payment_ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Supplier_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl Suppliers_tblField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Payment_Date {
            get {
                return this.Payment_DateField;
            }
            set {
                if ((this.Payment_DateField.Equals(value) != true)) {
                    this.Payment_DateField = value;
                    this.RaisePropertyChanged("Payment_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payment_Invoice_Id {
            get {
                return this.Payment_Invoice_IdField;
            }
            set {
                if ((this.Payment_Invoice_IdField.Equals(value) != true)) {
                    this.Payment_Invoice_IdField = value;
                    this.RaisePropertyChanged("Payment_Invoice_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Payment_Report Payment_Report {
            get {
                return this.Payment_ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.Payment_ReportField, value) != true)) {
                    this.Payment_ReportField = value;
                    this.RaisePropertyChanged("Payment_Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Supplier_Id {
            get {
                return this.Supplier_IdField;
            }
            set {
                if ((this.Supplier_IdField.Equals(value) != true)) {
                    this.Supplier_IdField = value;
                    this.RaisePropertyChanged("Supplier_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl Suppliers_tbl {
            get {
                return this.Suppliers_tblField;
            }
            set {
                if ((object.ReferenceEquals(this.Suppliers_tblField, value) != true)) {
                    this.Suppliers_tblField = value;
                    this.RaisePropertyChanged("Suppliers_tbl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment_Report", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Payment_Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Payment_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Payment_tbl Payment_tblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Report_NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Month {
            get {
                return this.MonthField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthField, value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payment_Id {
            get {
                return this.Payment_IdField;
            }
            set {
                if ((this.Payment_IdField.Equals(value) != true)) {
                    this.Payment_IdField = value;
                    this.RaisePropertyChanged("Payment_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Payment_tbl Payment_tbl {
            get {
                return this.Payment_tblField;
            }
            set {
                if ((object.ReferenceEquals(this.Payment_tblField, value) != true)) {
                    this.Payment_tblField = value;
                    this.RaisePropertyChanged("Payment_tbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Report_No {
            get {
                return this.Report_NoField;
            }
            set {
                if ((this.Report_NoField.Equals(value) != true)) {
                    this.Report_NoField = value;
                    this.RaisePropertyChanged("Report_No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Suppliers_tbl", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Suppliers_tbl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Item_tbl[] Item_tblsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] Payment_tblsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Phone_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Supplier_Bill_tbl[] Supplier_Bill_tblsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Supplier_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Supplier_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Item_tbl[] Item_tbls {
            get {
                return this.Item_tblsField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_tblsField, value) != true)) {
                    this.Item_tblsField = value;
                    this.RaisePropertyChanged("Item_tbls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] Payment_tbls {
            get {
                return this.Payment_tblsField;
            }
            set {
                if ((object.ReferenceEquals(this.Payment_tblsField, value) != true)) {
                    this.Payment_tblsField = value;
                    this.RaisePropertyChanged("Payment_tbls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Phone_No {
            get {
                return this.Phone_NoField;
            }
            set {
                if ((this.Phone_NoField.Equals(value) != true)) {
                    this.Phone_NoField = value;
                    this.RaisePropertyChanged("Phone_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Supplier_Bill_tbl[] Supplier_Bill_tbls {
            get {
                return this.Supplier_Bill_tblsField;
            }
            set {
                if ((object.ReferenceEquals(this.Supplier_Bill_tblsField, value) != true)) {
                    this.Supplier_Bill_tblsField = value;
                    this.RaisePropertyChanged("Supplier_Bill_tbls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Supplier_Id {
            get {
                return this.Supplier_IdField;
            }
            set {
                if ((this.Supplier_IdField.Equals(value) != true)) {
                    this.Supplier_IdField = value;
                    this.RaisePropertyChanged("Supplier_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Supplier_Name {
            get {
                return this.Supplier_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Supplier_NameField, value) != true)) {
                    this.Supplier_NameField = value;
                    this.RaisePropertyChanged("Supplier_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item_tbl", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Item_tbl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Item_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Stock_tbl[] Stock_tblsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Supplier_Bill_tbl[] Supplier_Bill_tblsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Supplier_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl Suppliers_tblField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Description {
            get {
                return this.Item_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_DescriptionField, value) != true)) {
                    this.Item_DescriptionField = value;
                    this.RaisePropertyChanged("Item_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Id {
            get {
                return this.Item_IdField;
            }
            set {
                if ((this.Item_IdField.Equals(value) != true)) {
                    this.Item_IdField = value;
                    this.RaisePropertyChanged("Item_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Name {
            get {
                return this.Item_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_NameField, value) != true)) {
                    this.Item_NameField = value;
                    this.RaisePropertyChanged("Item_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Stock_tbl[] Stock_tbls {
            get {
                return this.Stock_tblsField;
            }
            set {
                if ((object.ReferenceEquals(this.Stock_tblsField, value) != true)) {
                    this.Stock_tblsField = value;
                    this.RaisePropertyChanged("Stock_tbls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Supplier_Bill_tbl[] Supplier_Bill_tbls {
            get {
                return this.Supplier_Bill_tblsField;
            }
            set {
                if ((object.ReferenceEquals(this.Supplier_Bill_tblsField, value) != true)) {
                    this.Supplier_Bill_tblsField = value;
                    this.RaisePropertyChanged("Supplier_Bill_tbls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Supplier_Id {
            get {
                return this.Supplier_IdField;
            }
            set {
                if ((this.Supplier_IdField.Equals(value) != true)) {
                    this.Supplier_IdField = value;
                    this.RaisePropertyChanged("Supplier_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl Suppliers_tbl {
            get {
                return this.Suppliers_tblField;
            }
            set {
                if ((object.ReferenceEquals(this.Suppliers_tblField, value) != true)) {
                    this.Suppliers_tblField = value;
                    this.RaisePropertyChanged("Suppliers_tbl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier_Bill_tbl", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Supplier_Bill_tbl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Item_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Item_tbl Item_tblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Supplier_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl Suppliers_tblField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_Id {
            get {
                return this.Invoice_IdField;
            }
            set {
                if ((this.Invoice_IdField.Equals(value) != true)) {
                    this.Invoice_IdField = value;
                    this.RaisePropertyChanged("Invoice_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Id {
            get {
                return this.Item_IdField;
            }
            set {
                if ((this.Item_IdField.Equals(value) != true)) {
                    this.Item_IdField = value;
                    this.RaisePropertyChanged("Item_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Item_tbl Item_tbl {
            get {
                return this.Item_tblField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_tblField, value) != true)) {
                    this.Item_tblField = value;
                    this.RaisePropertyChanged("Item_tbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Supplier_Id {
            get {
                return this.Supplier_IdField;
            }
            set {
                if ((this.Supplier_IdField.Equals(value) != true)) {
                    this.Supplier_IdField = value;
                    this.RaisePropertyChanged("Supplier_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl Suppliers_tbl {
            get {
                return this.Suppliers_tblField;
            }
            set {
                if ((object.ReferenceEquals(this.Suppliers_tblField, value) != true)) {
                    this.Suppliers_tblField = value;
                    this.RaisePropertyChanged("Suppliers_tbl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock_tbl", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Stock_tbl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Current_Stock_LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Item_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Namal_WpfApplication.N_SServiceReference1.Item_tbl Item_tblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Reorder_LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Stock_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Current_Stock_Level {
            get {
                return this.Current_Stock_LevelField;
            }
            set {
                if ((this.Current_Stock_LevelField.Equals(value) != true)) {
                    this.Current_Stock_LevelField = value;
                    this.RaisePropertyChanged("Current_Stock_Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Id {
            get {
                return this.Item_IdField;
            }
            set {
                if ((this.Item_IdField.Equals(value) != true)) {
                    this.Item_IdField = value;
                    this.RaisePropertyChanged("Item_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Namal_WpfApplication.N_SServiceReference1.Item_tbl Item_tbl {
            get {
                return this.Item_tblField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_tblField, value) != true)) {
                    this.Item_tblField = value;
                    this.RaisePropertyChanged("Item_tbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Reorder_Limit {
            get {
                return this.Reorder_LimitField;
            }
            set {
                if ((this.Reorder_LimitField.Equals(value) != true)) {
                    this.Reorder_LimitField = value;
                    this.RaisePropertyChanged("Reorder_Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock_Id {
            get {
                return this.Stock_IdField;
            }
            set {
                if ((this.Stock_IdField.Equals(value) != true)) {
                    this.Stock_IdField = value;
                    this.RaisePropertyChanged("Stock_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="N_SServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_all_List", ReplyAction="http://tempuri.org/IService1/get_all_ListResponse")]
        Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] get_all_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_all_List", ReplyAction="http://tempuri.org/IService1/get_all_ListResponse")]
        System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_tbl[]> get_all_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_Payment_Id", ReplyAction="http://tempuri.org/IService1/get_Payment_IdResponse")]
        Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] get_Payment_Id(int P_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_Payment_Id", ReplyAction="http://tempuri.org/IService1/get_Payment_IdResponse")]
        System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_tbl[]> get_Payment_IdAsync(int P_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_Payment", ReplyAction="http://tempuri.org/IService1/Add_PaymentResponse")]
        void Add_Payment(int P_Id, System.DateTime date, float Amount, int Supplier_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_Payment", ReplyAction="http://tempuri.org/IService1/Add_PaymentResponse")]
        System.Threading.Tasks.Task Add_PaymentAsync(int P_Id, System.DateTime date, float Amount, int Supplier_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Search_Payments", ReplyAction="http://tempuri.org/IService1/Search_PaymentsResponse")]
        string[] Search_Payments(int P_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Search_Payments", ReplyAction="http://tempuri.org/IService1/Search_PaymentsResponse")]
        System.Threading.Tasks.Task<string[]> Search_PaymentsAsync(int P_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePayment", ReplyAction="http://tempuri.org/IService1/DeletePaymentResponse")]
        void DeletePayment(int P_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePayment", ReplyAction="http://tempuri.org/IService1/DeletePaymentResponse")]
        System.Threading.Tasks.Task DeletePaymentAsync(int P_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPayments", ReplyAction="http://tempuri.org/IService1/GetAllPaymentsResponse")]
        Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] GetAllPayments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPayments", ReplyAction="http://tempuri.org/IService1/GetAllPaymentsResponse")]
        System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_tbl[]> GetAllPaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaymentReport", ReplyAction="http://tempuri.org/IService1/GetPaymentReportResponse")]
        Namal_WpfApplication.N_SServiceReference1.Payment_Report[] GetPaymentReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaymentReport", ReplyAction="http://tempuri.org/IService1/GetPaymentReportResponse")]
        System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_Report[]> GetPaymentReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_pass", ReplyAction="http://tempuri.org/IService1/get_passResponse")]
        string get_pass(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_pass", ReplyAction="http://tempuri.org/IService1/get_passResponse")]
        System.Threading.Tasks.Task<string> get_passAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSupplierDetails", ReplyAction="http://tempuri.org/IService1/InsertSupplierDetailsResponse")]
        string InsertSupplierDetails(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSupplierDetails", ReplyAction="http://tempuri.org/IService1/InsertSupplierDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertSupplierDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSupplierDetails", ReplyAction="http://tempuri.org/IService1/UpdateSupplierDetailsResponse")]
        string UpdateSupplierDetails(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSupplierDetails", ReplyAction="http://tempuri.org/IService1/UpdateSupplierDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateSupplierDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSupplierDetails", ReplyAction="http://tempuri.org/IService1/DeleteSupplierDetailsResponse")]
        string DeleteSupplierDetails(int Supplier_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSupplierDetails", ReplyAction="http://tempuri.org/IService1/DeleteSupplierDetailsResponse")]
        System.Threading.Tasks.Task<string> DeleteSupplierDetailsAsync(int Supplier_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/nextSupplierID", ReplyAction="http://tempuri.org/IService1/nextSupplierIDResponse")]
        int nextSupplierID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/nextSupplierID", ReplyAction="http://tempuri.org/IService1/nextSupplierIDResponse")]
        System.Threading.Tasks.Task<int> nextSupplierIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SupplierDetails", ReplyAction="http://tempuri.org/IService1/SupplierDetailsResponse")]
        string SupplierDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SupplierDetails", ReplyAction="http://tempuri.org/IService1/SupplierDetailsResponse")]
        System.Threading.Tasks.Task<string> SupplierDetailsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertItemDetails", ReplyAction="http://tempuri.org/IService1/InsertItemDetailsResponse")]
        string InsertItemDetails(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertItemDetails", ReplyAction="http://tempuri.org/IService1/InsertItemDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertItemDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItemDetails", ReplyAction="http://tempuri.org/IService1/UpdateItemDetailsResponse")]
        string UpdateItemDetails(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItemDetails", ReplyAction="http://tempuri.org/IService1/UpdateItemDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateItemDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteItemDetails", ReplyAction="http://tempuri.org/IService1/DeleteItemDetailsResponse")]
        string DeleteItemDetails(int item_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteItemDetails", ReplyAction="http://tempuri.org/IService1/DeleteItemDetailsResponse")]
        System.Threading.Tasks.Task<string> DeleteItemDetailsAsync(int item_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/nextItemID", ReplyAction="http://tempuri.org/IService1/nextItemIDResponse")]
        int nextItemID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/nextItemID", ReplyAction="http://tempuri.org/IService1/nextItemIDResponse")]
        System.Threading.Tasks.Task<int> nextItemIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ItemDetails", ReplyAction="http://tempuri.org/IService1/ItemDetailsResponse")]
        string ItemDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ItemDetails", ReplyAction="http://tempuri.org/IService1/ItemDetailsResponse")]
        System.Threading.Tasks.Task<string> ItemDetailsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ItemDetailsByItmID", ReplyAction="http://tempuri.org/IService1/ItemDetailsByItmIDResponse")]
        Namal_WpfApplication.N_SServiceReference1.Item_tbl[] ItemDetailsByItmID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ItemDetailsByItmID", ReplyAction="http://tempuri.org/IService1/ItemDetailsByItmIDResponse")]
        System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Item_tbl[]> ItemDetailsByItmIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ItemDetailsByItmName", ReplyAction="http://tempuri.org/IService1/ItemDetailsByItmNameResponse")]
        Namal_WpfApplication.N_SServiceReference1.Item_tbl[] ItemDetailsByItmName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ItemDetailsByItmName", ReplyAction="http://tempuri.org/IService1/ItemDetailsByItmNameResponse")]
        System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Item_tbl[]> ItemDetailsByItmNameAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStockDetails", ReplyAction="http://tempuri.org/IService1/InsertStockDetailsResponse")]
        string InsertStockDetails(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStockDetails", ReplyAction="http://tempuri.org/IService1/InsertStockDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertStockDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStockDetails", ReplyAction="http://tempuri.org/IService1/UpdateStockDetailsResponse")]
        string UpdateStockDetails(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStockDetails", ReplyAction="http://tempuri.org/IService1/UpdateStockDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateStockDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStockDetails", ReplyAction="http://tempuri.org/IService1/DeleteStockDetailsResponse")]
        string DeleteStockDetails(int Stock_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStockDetails", ReplyAction="http://tempuri.org/IService1/DeleteStockDetailsResponse")]
        System.Threading.Tasks.Task<string> DeleteStockDetailsAsync(int Stock_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockDetails", ReplyAction="http://tempuri.org/IService1/StockDetailsResponse")]
        string StockDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockDetails", ReplyAction="http://tempuri.org/IService1/StockDetailsResponse")]
        System.Threading.Tasks.Task<string> StockDetailsAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Namal_WpfApplication.N_SServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Namal_WpfApplication.N_SServiceReference1.IService1>, Namal_WpfApplication.N_SServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] get_all_List() {
            return base.Channel.get_all_List();
        }
        
        public System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_tbl[]> get_all_ListAsync() {
            return base.Channel.get_all_ListAsync();
        }
        
        public Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] get_Payment_Id(int P_Id) {
            return base.Channel.get_Payment_Id(P_Id);
        }
        
        public System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_tbl[]> get_Payment_IdAsync(int P_Id) {
            return base.Channel.get_Payment_IdAsync(P_Id);
        }
        
        public void Add_Payment(int P_Id, System.DateTime date, float Amount, int Supplier_Id) {
            base.Channel.Add_Payment(P_Id, date, Amount, Supplier_Id);
        }
        
        public System.Threading.Tasks.Task Add_PaymentAsync(int P_Id, System.DateTime date, float Amount, int Supplier_Id) {
            return base.Channel.Add_PaymentAsync(P_Id, date, Amount, Supplier_Id);
        }
        
        public string[] Search_Payments(int P_id) {
            return base.Channel.Search_Payments(P_id);
        }
        
        public System.Threading.Tasks.Task<string[]> Search_PaymentsAsync(int P_id) {
            return base.Channel.Search_PaymentsAsync(P_id);
        }
        
        public void DeletePayment(int P_id) {
            base.Channel.DeletePayment(P_id);
        }
        
        public System.Threading.Tasks.Task DeletePaymentAsync(int P_id) {
            return base.Channel.DeletePaymentAsync(P_id);
        }
        
        public Namal_WpfApplication.N_SServiceReference1.Payment_tbl[] GetAllPayments() {
            return base.Channel.GetAllPayments();
        }
        
        public System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_tbl[]> GetAllPaymentsAsync() {
            return base.Channel.GetAllPaymentsAsync();
        }
        
        public Namal_WpfApplication.N_SServiceReference1.Payment_Report[] GetPaymentReport() {
            return base.Channel.GetPaymentReport();
        }
        
        public System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Payment_Report[]> GetPaymentReportAsync() {
            return base.Channel.GetPaymentReportAsync();
        }
        
        public string get_pass(string id) {
            return base.Channel.get_pass(id);
        }
        
        public System.Threading.Tasks.Task<string> get_passAsync(string id) {
            return base.Channel.get_passAsync(id);
        }
        
        public string InsertSupplierDetails(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo) {
            return base.Channel.InsertSupplierDetails(SupplierInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertSupplierDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo) {
            return base.Channel.InsertSupplierDetailsAsync(SupplierInfo);
        }
        
        public string UpdateSupplierDetails(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo) {
            return base.Channel.UpdateSupplierDetails(SupplierInfo);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSupplierDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Suppliers_tbl SupplierInfo) {
            return base.Channel.UpdateSupplierDetailsAsync(SupplierInfo);
        }
        
        public string DeleteSupplierDetails(int Supplier_ID) {
            return base.Channel.DeleteSupplierDetails(Supplier_ID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteSupplierDetailsAsync(int Supplier_ID) {
            return base.Channel.DeleteSupplierDetailsAsync(Supplier_ID);
        }
        
        public int nextSupplierID() {
            return base.Channel.nextSupplierID();
        }
        
        public System.Threading.Tasks.Task<int> nextSupplierIDAsync() {
            return base.Channel.nextSupplierIDAsync();
        }
        
        public string SupplierDetails(int id) {
            return base.Channel.SupplierDetails(id);
        }
        
        public System.Threading.Tasks.Task<string> SupplierDetailsAsync(int id) {
            return base.Channel.SupplierDetailsAsync(id);
        }
        
        public string InsertItemDetails(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo) {
            return base.Channel.InsertItemDetails(ItemInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertItemDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo) {
            return base.Channel.InsertItemDetailsAsync(ItemInfo);
        }
        
        public string UpdateItemDetails(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo) {
            return base.Channel.UpdateItemDetails(ItemInfo);
        }
        
        public System.Threading.Tasks.Task<string> UpdateItemDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Item_tbl ItemInfo) {
            return base.Channel.UpdateItemDetailsAsync(ItemInfo);
        }
        
        public string DeleteItemDetails(int item_Id) {
            return base.Channel.DeleteItemDetails(item_Id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteItemDetailsAsync(int item_Id) {
            return base.Channel.DeleteItemDetailsAsync(item_Id);
        }
        
        public int nextItemID() {
            return base.Channel.nextItemID();
        }
        
        public System.Threading.Tasks.Task<int> nextItemIDAsync() {
            return base.Channel.nextItemIDAsync();
        }
        
        public string ItemDetails(int id) {
            return base.Channel.ItemDetails(id);
        }
        
        public System.Threading.Tasks.Task<string> ItemDetailsAsync(int id) {
            return base.Channel.ItemDetailsAsync(id);
        }
        
        public Namal_WpfApplication.N_SServiceReference1.Item_tbl[] ItemDetailsByItmID(string id) {
            return base.Channel.ItemDetailsByItmID(id);
        }
        
        public System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Item_tbl[]> ItemDetailsByItmIDAsync(string id) {
            return base.Channel.ItemDetailsByItmIDAsync(id);
        }
        
        public Namal_WpfApplication.N_SServiceReference1.Item_tbl[] ItemDetailsByItmName(string Name) {
            return base.Channel.ItemDetailsByItmName(Name);
        }
        
        public System.Threading.Tasks.Task<Namal_WpfApplication.N_SServiceReference1.Item_tbl[]> ItemDetailsByItmNameAsync(string Name) {
            return base.Channel.ItemDetailsByItmNameAsync(Name);
        }
        
        public string InsertStockDetails(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo) {
            return base.Channel.InsertStockDetails(StockInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertStockDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo) {
            return base.Channel.InsertStockDetailsAsync(StockInfo);
        }
        
        public string UpdateStockDetails(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo) {
            return base.Channel.UpdateStockDetails(StockInfo);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStockDetailsAsync(Namal_WpfApplication.N_SServiceReference1.Stock_tbl StockInfo) {
            return base.Channel.UpdateStockDetailsAsync(StockInfo);
        }
        
        public string DeleteStockDetails(int Stock_Id) {
            return base.Channel.DeleteStockDetails(Stock_Id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteStockDetailsAsync(int Stock_Id) {
            return base.Channel.DeleteStockDetailsAsync(Stock_Id);
        }
        
        public string StockDetails(int id) {
            return base.Channel.StockDetails(id);
        }
        
        public System.Threading.Tasks.Task<string> StockDetailsAsync(int id) {
            return base.Channel.StockDetailsAsync(id);
        }
    }
}
